version: '3.8'

services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx-container
    ports:
      - 9000:80
    volumes:
      - ./nginx-templates:/etc/nginx/templates:ro
    environment:
      - DASHBOARD_URL=http://dashboard:80
      - SOLVER_API_URL=http://solverApi:3000/
      - SOLVER_API_WS_URI=http://solverApi:3002
    depends_on:
      - dashboard
      - solverApi

  dashboard:
    container_name: dashboard-container
    image: dashboard-image
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        - REACT_APP_SOLVER_API_URL=http://localhost:9000/solver-api/
        - REACT_APP_NOTIFICATIONS_URI=ws://localhost:9000

  solverApi:
    container_name: solver-api-container
    image: solver-api-image
    build:
      context: ./solver-api
      dockerfile: Dockerfile
    environment:
      - PORT=3000
