version: '3.8'

services:
  dashboard:
    container_name: dashboard-container
    image: dashboard-image
    build:
      context: ./dashboard/
      dockerfile: Dockerfile
    ports:
      - 9000:80
    environment:
      - REACT_APP_NOTIFICATIONS_URI=ws://solver:3002
      - REACT_APP_SOLVER_API_URL=http://solver:3001
